name: Generate recipes list

on:
  push:
    paths:
      - "lib/recipes.ts"
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Generate recipes list
        run: node ./scripts/generate-recipes-list.mjs
      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add RECIPES_LIST.txt || true
          if ! git diff --staged --quiet; then
            git commit -m "chore: update RECIPES_LIST.txt"
            git push
          else
            echo 'No changes to commit.'
          fi
